# -*- coding: utf-8 -*-
"""AlgaeEDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bqJXiUjEVMdrrwN3_OztTtJ75ZyEVlsQ

**Dataset Overview, Data Cleaning, and Exploratory Data Analysis (EDA)**

**Kaggle Dataset "Research on Algae Growth"**
"""

import pandas as pd
df = pd.read_csv('/content/algeas (1).csv')

df.info()

"""There are no null values in the dataset."""

df.describe()

"""* Units are stated in the dataset page of Kaggle as: Light (μmol photons/m²/s), Nitrate (mg/L), Phosphate (mg/L), Iron (mg/L), Temperature (°C), pH, Carbon Dioxide (CO2) (mg/L). The Population's unit was not expressed; assumption is that it is an index precalculated by some growth parameters; it can be considered as a score of growth.
* All values are observed to be between normal ranges except zero values of algae, it should be examined further.
"""

zero_population_data = df[df['Population'] == 0]
zero_population_data

zero_population_data.describe()

nonzero_population_data = df[df['Population'] != 0]
nonzero_population_data.describe()

description_stats = nonzero_population_data.describe()
mean_std_stats = description_stats.loc[['mean', 'std']]
mean_std_stats

description_stats_zeros = zero_population_data.describe()
mean_std_stats_zeros = description_stats_zeros.loc[['mean', 'std']]
mean_std_stats_zeros

"""As seen in the stats above, the conditions are nearly the same for population=0 and population!=0 data."""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12, 9))
for col in df.columns:
  plt.subplot(3, 3, df.columns.get_loc(col) + 1)
  sns.histplot(df[col])
  plt.title(f'Distribution of {col}')
  plt.xlabel(col)
  plt.ylabel('Frequency')
  plt.grid(True)

plt.tight_layout()
plt.show()

"""No anomalies in the distribution of the data, the spike at 0 for Population is an ordinary phenomenon for datasets; no need for handling."""

plt.figure(figsize=(12, 9))
for i, col in enumerate(df):
    plt.subplot(3, 3, i + 1)
    sns.boxplot(y=df[col])
    plt.title(f'Box Plot of {col}')
    plt.ylabel('')
plt.tight_layout()
plt.show()

"""There are no depicted outliers in the boxplot, further investigation needed to detect potential outliers."""

for col in df.columns:
  Q1 = df[col].quantile(0.25)
  Q3 = df[col].quantile(0.75)
  IQR = Q3 - Q1
  lower_bound = Q1 - 1.5 * IQR
  upper_bound = Q3 + 1.5 * IQR

  outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]

  if not outliers.empty:
      print(f"Feature: {col}")
      print(f"Q1: {Q1:.2f}, Q3: {Q3:.2f}, IQR: {IQR:.2f}")
      print(f"Lower Bound: {lower_bound:.2f}, Upper Bound: {upper_bound:.2f}")
      print(f"Number of Outliers: {len(outliers)}")
      print("\n")
  else:
      print(f"{col}: No outliers")

"""All features were examined by the IQR*1.5 rule for outliers, none of the features have outliers in the dataset which indicates that there is no need for outlier cleaning."""

correlation_matrix = df.corr()

plt.figure(figsize=(5, 4))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix')
plt.show()

"""There is no significant correlation between features. This might indicate that the quality of dataset is low or the parameters are in a perfect mix on impacting the algae growth.

**Coil 1999 Competition Data**
"""

df_coil = pd.read_csv('/content/analysis.data', sep=',', header=None)
df_coil.head()

"""Data columns were missing in original instructions at [ICS Website](https://archive.ics.uci.edu/dataset/118/coil+1999+competition+data). Another source mentions what columns are indicating (Vadlapatla, K. Data Mining with R Learning with Case Studies).


* Maximum pH value
* Minimum value of O2 (oxygen)
* Mean value of Cl (chloride)
* Mean value of NO−3 (nitrates)
* Mean value of NH+4 (ammonium)
* Mean of PO3−4 (orthophosphate)
* Mean of total PO4 (phosphate)
* Mean of chlorophyll
* Frequencies of different algae groups (last 7 columns)
"""

column_names = [
    'Season', 'Size', 'River_Size',
    'Max_pH', 'Min_O2', 'Mean_Cl', 'Mean_NO3', 'Mean_NH4',
    'Mean_Orthophosphate', 'Mean_Phosphate', 'Mean_Chlorophyll',
    'Algae_Group_1', 'Algae_Group_2', 'Algae_Group_3', 'Algae_Group_4', 'Algae_Group_5', 'Algae_Group_6', 'Algae_Group_7'
]
df_coil.columns = column_names
df_coil.head()

df_coil.info()

"""The numerical values are object type, they are needed to be converted to float."""

for col_name in df_coil.columns[0:3]:
    df_coil[col_name] = df_coil[col_name].astype(str)

for col_name in df_coil.columns[3:]:
    df_coil[col_name] = pd.to_numeric(df_coil[col_name], errors='coerce').fillna(0).astype(float)

df_coil.info()

df_coil.describe()

numerical_df_coil = df_coil.iloc[:, 3:]
correlation_matrix = numerical_df_coil.corr()

plt.figure(figsize=(9, 7))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix of Numerical Features in df_coil')
plt.show()

"""Some of the features have relatively high correlation rates (>|0.40|):

* Mean_NO3 vs Mean_Phosphate: 0.47
* Mean_Cl vs Mean_Phosphate: 0.44
* Mean_Phosphate vs Mean_Chlorophyll: 0.41
* Mean_Chlorophyll vs Algae_Group_2: 0.41
* Mean_Phosphate vs Algae_Group_1: -0.47

Altough some are high, the ranges are below the standards for significant correlations.
"""

plt.figure(figsize=(12, 9))
for col in df_coil.columns[0:3]:
  plt.subplot(3, 3, df_coil.columns.get_loc(col) + 1)
  sns.histplot(df_coil[col])
  plt.title(f'Distribution of {col}')
  plt.xlabel(col)
  plt.ylabel('Frequency')
  plt.grid(True)

plt.tight_layout()
plt.show()

"""These plots show that the COIL dataset is fairly balanced across Seasons and Size categories, while River_Size is slightly skewed toward medium and high sites with fewer low-size rivers."""

numerical_cols = df_coil.columns[3:]
num_plots = len(numerical_cols)
num_cols = 4
num_rows = (num_plots + num_cols - 1) // num_cols

plt.figure(figsize=(num_cols * 3, num_rows * 3))

for i, col in enumerate(numerical_cols):
    plt.subplot(num_rows, num_cols, i + 1)
    sns.boxplot(y=df_coil[col])
    plt.title(f'Box Plot of {col}')
    plt.ylabel('')
    plt.tick_params(axis='y', labelsize=8)
plt.tight_layout()
plt.show()

"""Many outliers are observed in all features, these will need to be handled."""

for col in df_coil.columns[3:]:
    Q1 = df_coil[col].quantile(0.25)
    Q3 = df_coil[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df_coil[(df_coil[col] < lower_bound) | (df_coil[col] > upper_bound)]

    if not outliers.empty:
        print(f"{col}, number of outliers: {len(outliers)}")

"""As seen above, the number of outliers are pretty high considering there are 200 rows."""

outlier_rows = set()

for col in df_coil.columns[3:]:
    Q1 = df_coil[col].quantile(0.25)
    Q3 = df_coil[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    current_col_outliers = df_coil[(df_coil[col] < lower_bound) | (df_coil[col] > upper_bound)].index

    outlier_rows.update(current_col_outliers)

print(f"Number of rows with at least one outlier: {len(outlier_rows)}")

"""As observed, 123 of 200 rows has at least one outlier feature which indicates the outlier handling should be sensitive; elimination would be fatal. Correct approach is implementing log transformation after analyzing skews."""

numerical_cols = df_coil.columns[3:]
num_plots = len(numerical_cols)

num_cols_grid = 4
num_rows_grid = (num_plots + num_cols_grid - 1) // num_cols_grid

plt.figure(figsize=(num_cols_grid * 4, num_rows_grid * 3))

for i, col in enumerate(numerical_cols):
    plt.subplot(num_rows_grid, num_cols_grid, i + 1)
    sns.histplot(df_coil[col], kde=True)
    plt.title(f'Distribution of {col}')
    plt.xlabel(col)
    plt.ylabel('Frequency')
    plt.grid(True)

plt.tight_layout()
plt.show()

"""As seen above the features except O2 and pH are right skewed, so they need log transformation."""

import numpy as np
numerical_cols_to_transform = [col for col in df_coil.columns[3:] if col not in ['Max_pH', 'Min_O2']]

for col in numerical_cols_to_transform:
    df_coil[col] = np.log1p(df_coil[col])

df_coil.head()

numerical_cols = df_coil.columns[3:]
num_plots = len(numerical_cols)
num_cols = 4
num_rows = (num_plots + num_cols - 1) // num_cols

plt.figure(figsize=(num_cols * 3, num_rows * 3))

for i, col in enumerate(numerical_cols):
    plt.subplot(num_rows, num_cols, i + 1)
    sns.boxplot(y=df_coil[col])
    plt.title(f'Box Plot of {col}')
    plt.ylabel('')
    plt.tick_params(axis='y', labelsize=8)
plt.tight_layout()
plt.show()

"""As seen in the boxplot above, the log transformation significantly decreased number of outliers."""

numerical_df_coil = df_coil.iloc[:, 3:]
correlation_matrix = numerical_df_coil.corr()

plt.figure(figsize=(9, 7))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix of Numerical Features in df_coil (After Corrected Transformation)')
plt.show()

"""After log-transforming the skewed variables, correlations became clearer and more linear, with moderate positive associations emerging among nutrients (e.g., Cl-Orthophosphate: 0.79, NO3-Phosphate: 0.56) and between nutrients and chlorophyll (around 0.59). Algal groups still show mostly weak to moderate links, reflecting species-specific responses. Overall, the transformed matrix gives a cleaner and more reliable view than the raw correlations, though most relationships remain moderate rather than strong.

Both datasets are analyzed and prepared for further processes in the project.
"""