# -*- coding: utf-8 -*-
"""AlgaeHypothesisTesting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R2I-kbds42hnno0ke5XSXxPmUvetvFVz

**Hypothesis Testing**

**Definition of Hypothesis**

We aim to examine whether there is a meaningful relationship between light intensity and algal growth in Kaggle dataset.

**H0 (Null Hypothesis):** There is no statistically significant linear correlation between Light intensity and Algal Growth.

**H1 (Alternative Hypothesis):** There is a statistically significant linear correlation between Light intensity and Algal Growth.

We will test this hypothesis using the Pearson correlation coefficient to evaluate whether Light intensity is linearly associated with Algal Growth in the experimental dataset. If no significant correlation is found, it supports the conclusion from the EDA that population dynamics in this experiment are driven by non-linear effects or interactions rather than a single linear factor such as light.
"""

import pandas as pd
df = pd.read_csv('/content/algeas (1).csv')

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
plt.scatter(df['Light'], df['Population'])
plt.xlabel('Light Intensity')
plt.ylabel('Population')
plt.title('Scatterplot of Light Intensity vs. Population')
plt.grid(True)
plt.show()

"""As seen above, the correlation exists but not linear, the hypothesis testing probably will yield no linear correlation."""

from scipy.stats import pearsonr

correlation_coefficient, p_value = pearsonr(df['Light'], df['Population'])

degrees_of_freedom = len(df['Light']) - 2

print(f"Pearson Correlation Coefficient: {correlation_coefficient:.4f}")
print(f"p-value: {p_value:.4f}")
print(f"Degrees of Freedom: {degrees_of_freedom}")

"""The Pearson test returned a near-zero correlation (r = 0.0062) with a high p-value (p = 0.5368), indicating no statistically significant linear relationship between Light intensity and Population. This aligns with the scatterplot, which shows a strong U-shaped non-linear pattern that Pearson correlation cannot capture."""